added animations
scipion-em/scipion-em-prody pull request #2
Opened 2022-03-10 18:50 UTC by jamesmkrieger

The animation step uses a combination of ProDy traverseMode and the vmd script generator from continuous flex.

2022-04-09 17:01 UTC, MohamadHarastani approved these changes

2022-05-11 09:59 UTC, fedher0 requested changes

2022-05-11 09:59 UTC, fedher0 commented on prody2/protocols/protocol_anm.py
> +            prody.writePDB(fnAnimation+".pdb",
could be better to separate as in the defvec case

2022-05-11 09:59 UTC, fedher0 commented on prody2/protocols/protocol_defvec.py
> +        self._insertFunctionStep('computeAtomShiftsStep')
this probably shouldn´t be here. Also merge with master and resolve conflicts related to it now being there.

2022-05-11 10:06 UTC, fedher0 approved these changes

2022-05-11 10:07 UTC, merged